package com.ge.treasury.myfunding.domain.myfunding;

import java.util.Date;
import java.util.List;

import com.ge.treasury.myfunding.domain.BaseDomainObject;

public class Deal extends BaseDomainObject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_ID
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private Integer dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_DISPLAY
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dealDisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_NAME
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_STATUS_CODE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dealStatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DAY_CODE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUESTER
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dealRequester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REASON
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
   

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_PRIORITY
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dealPriority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.PRIORITY_COMMENT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String priorityComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.RESPONSIBLE_TEAM
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String responsibleTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.AFFIRM_DUE_DATE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private Date affirmDueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_TAX_CONTACT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String busTaxContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_CONTROLLER_CONTACT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String busControllerContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUEST_TIMESTAMP
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private Date dealRequestTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_RATIONALE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    private String dealRationale;

    /**
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.USD_EQUIVALENT_AMOUNT
     *
     * @generated Wed My 24 16:00:00 EDT 2017
     */
    private Double usdEquivalentAmount;

    /**
     * This field corresponds to the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.MDM_BUSINESS_TYPE
     *
     * @generated Wed My 24 16:00:00 EDT 2017
     */
    private String mdmBusinessType;
    
    //sonar fix
    private List<Transaction> transactions;
    private List<Document> documents;
    private List<Team> teams;
    
    private boolean readOnly = true;
    
    private String action;
    
    public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public boolean isReadOnly() {
        return readOnly;
    }
    
    public void setReadOnly(boolean readOnly) {
        this.readOnly = readOnly;
    }
    
    public List<Transaction> getTransactions() {
        return transactions;
    }

    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
    }

    public List<Document> getDocuments() {
        return documents;
    }

    public void setDocuments(List<Document> documents) {
        this.documents = documents;
    }

    public List<Team> getTeams() {
        return teams;
    }

    public void setTeams(List<Team> teams) {
        this.teams = teams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_ID
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_ID
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_ID
     *
     * @param dealId the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_ID
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_DISPLAY
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_DISPLAY
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDealDisplay() {
        return dealDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_DISPLAY
     *
     * @param dealDisplay the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_DISPLAY
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealDisplay(String dealDisplay) {
        this.dealDisplay = dealDisplay == null ? null : dealDisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_NAME
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_NAME
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDealName() {
        return dealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_NAME
     *
     * @param dealName the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_NAME
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealName(String dealName) {
        this.dealName = dealName == null ? null : dealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_STATUS_CODE
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_STATUS_CODE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDealStatusCode() {
        return dealStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_STATUS_CODE
     *
     * @param dealStatusCode the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_STATUS_CODE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealStatusCode(String dealStatusCode) {
        this.dealStatusCode = dealStatusCode == null ? null : dealStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DAY_CODE
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DAY_CODE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDayCode() {
        return dayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DAY_CODE
     *
     * @param dayCode the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DAY_CODE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDayCode(String dayCode) {
        this.dayCode = dayCode == null ? null : dayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUESTER
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUESTER
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDealRequester() {
        return dealRequester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUESTER
     *
     * @param dealRequester the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUESTER
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealRequester(String dealRequester) {
        this.dealRequester = dealRequester == null ? null : dealRequester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REASON
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REASON
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_PRIORITY
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_PRIORITY
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDealPriority() {
        return dealPriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_PRIORITY
     *
     * @param dealPriority the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_PRIORITY
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealPriority(String dealPriority) {
        this.dealPriority = dealPriority == null ? null : dealPriority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.PRIORITY_COMMENT
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.PRIORITY_COMMENT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getPriorityComment() {
        return priorityComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.PRIORITY_COMMENT
     *
     * @param priorityComment the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.PRIORITY_COMMENT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setPriorityComment(String priorityComment) {
        this.priorityComment = priorityComment == null ? null : priorityComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.RESPONSIBLE_TEAM
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.RESPONSIBLE_TEAM
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getResponsibleTeam() {
        return responsibleTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.RESPONSIBLE_TEAM
     *
     * @param responsibleTeam the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.RESPONSIBLE_TEAM
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setResponsibleTeam(String responsibleTeam) {
        this.responsibleTeam = responsibleTeam == null ? null : responsibleTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.AFFIRM_DUE_DATE
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.AFFIRM_DUE_DATE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public Date getAffirmDueDate() {
        return affirmDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.AFFIRM_DUE_DATE
     *
     * @param affirmDueDate the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.AFFIRM_DUE_DATE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setAffirmDueDate(Date affirmDueDate) {
        this.affirmDueDate = affirmDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_TAX_CONTACT
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_TAX_CONTACT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getBusTaxContact() {
        return busTaxContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_TAX_CONTACT
     *
     * @param busTaxContact the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_TAX_CONTACT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setBusTaxContact(String busTaxContact) {
        this.busTaxContact = busTaxContact == null ? null : busTaxContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_CONTROLLER_CONTACT
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_CONTROLLER_CONTACT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getBusControllerContact() {
        return busControllerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_CONTROLLER_CONTACT
     *
     * @param busControllerContact the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.BUS_CONTROLLER_CONTACT
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setBusControllerContact(String busControllerContact) {
        this.busControllerContact = busControllerContact == null ? null : busControllerContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUEST_TIMESTAMP
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUEST_TIMESTAMP
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public Date getDealRequestTimestamp() {
        return dealRequestTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUEST_TIMESTAMP
     *
     * @param dealRequestTimestamp the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_REQUEST_TIMESTAMP
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealRequestTimestamp(Date dealRequestTimestamp) {
        this.dealRequestTimestamp = dealRequestTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_RATIONALE
     *
     * @return the value of MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_RATIONALE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public String getDealRationale() {
        return dealRationale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_RATIONALE
     *
     * @param dealRationale the value for MYFUNDING.T_MYFUND_DEAL_REQUEST.DEAL_RATIONALE
     *
     * @mbg.generated Sat Mar 25 12:44:07 EDT 2017
     */
    public void setDealRationale(String dealRationale) {
        this.dealRationale = dealRationale == null ? null : dealRationale.trim();
    }
    
    /**
     * @return the usdEquivalentAmount
     */
    public Double getUsdEquivalentAmount() {
        return usdEquivalentAmount;
    }

    /**
     * @param usdEquivalentAmount the usdEquivalentAmount to set
     */
    public void setUsdEquivalentAmount(Double usdEquivalentAmount) {
        this.usdEquivalentAmount = usdEquivalentAmount;
    }

    /**
     * @return the mdmBusinessType
     */
    public String getMdmBusinessType() {
        return mdmBusinessType;
    }

    /**
     * @param mdmBusinessType the mdmBusinessType to set
     */
    public void setMdmBusinessType(String mdmBusinessType) {
        this.mdmBusinessType = mdmBusinessType;
    }

    @Override
    public String toString() {
        return "Deal [id=" + dealId + ", status=" + dealStatusCode + ", name=" + dealName + ", rationale=" + dealRationale + ", priority="
                + dealPriority + ", priorityComment=" + priorityComment + ", responsibleTeam=" + responsibleTeam
                + ", affirmationDueDate=" + affirmDueDate + ", isDay12=" + dayCode + ", dealRequester="
                + dealRequester + ", requestDate=" + dealRequestTimestamp + ", busTaxContact=" + busTaxContact
                + ", busController=" + busControllerContact + ", createUser=" + createUser + ", lastUpdateUser=" + lastUpdateUser 
                + ", createTimestamp=" + createTimestamp + ", lastUpdateTimestamp=" + getLastUpdateTimestamp()
                + ", Transactions= " + transactions 
                + ", Documents= " + documents 
                + ", Teams= " + teams
                + ", readOnly= " + readOnly
                + "]";
    }
}
